In [1]:
import numpy as np

np.random.seed(42)

In [2]:
arr = np.random.rand(100, 100)
arr.shape # (100, 100)

(100, 100)

In [3]:
def manual_mean(x):
    total = 0.0
    for row in x:
        for val in row:
            total += val
    return total / x.size

In [4]:
%timeit manual_mean(arr)
%timeit np.mean(arr)

970 μs ± 25.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
9.05 μs ± 587 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [12]:
arr_r = arr.reshape(20, 500)
print(arr[:5, :5])
print(arr[arr > 0.9])
v = np.random.rand(100)
print(v)
print(arr.dot(v))
arr_norm = (arr - arr.mean()) / arr.std()
print(arr_norm)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.03142919 0.63641041 0.31435598 0.50857069 0.90756647]
 [0.64203165 0.08413996 0.16162871 0.89855419 0.60642906]
 [0.05168172 0.53135463 0.54063512 0.6374299  0.72609133]
 [0.10312387 0.90255291 0.50525237 0.82645747 0.3200496 ]]
[0.95071431 0.96990985 0.94888554 0.96563203 0.9093204  0.96958463
 0.93949894 0.92187424 0.98688694 0.90756647 0.92969765 0.9429097
 0.97178208 0.96244729 0.90826589 0.98565045 0.93672999 0.92469362
 0.90041806 0.97301055 0.94045858 0.95392858 0.91486439 0.92831856
 0.96665482 0.96361998 0.93615477 0.99005385 0.91324055 0.97585208
 0.96264841 0.95486528 0.94023024 0.94146481 0.96119056 0.90535064
 0.99050514 0.93075733 0.90255291 0.90538198 0.95006197 0.95060715
 0.98663958 0.94724858 0.98600106 0.90635439 0.96217255 0.96322254
 0.96987883 0.9929648  0.96930254 0.90115801 0.95041148 0.97439481
 0.98621074 0.91092718 0.94979991 0.93272848 0.98727613 0.9699144
 0.99971767 0.99663684 0.94476573 0.95405